#ifndef __CHIPDEF_H__
#define __CHIPDEF_H__

// chip related constant & function definition

#if defined(CONFIG_TARGET_PRX126)
#define CHIP_NAME			"PX126"
#endif
#if defined(CONFIG_TARGET_PRX120)
#define CHIP_NAME			"PX120"
#endif
#if defined(CONFIG_TARGET_PRX321)
#define CHIP_NAME			"PX321"
#endif

#if defined(CONFIG_TARGET_PRX126) || defined CONFIG_SDK_PRX120 || defined CONFIG_SDK_PRX321
#define CHIP_PON_PORTID			2
#define CHIP_PORTMASK			0xD		// uni:0..3, pon:4, rgmii:5, cpu:6
#define CHIP_EXTPORTMASK		0x1		// 0..5
#define CHIP_PORT_TOTAL			4
#define CHIP_RG_PORT_TOTAL		4
#define CHIP_GPON_TCONT_GROUP		1
#define CHIP_L2_LEARN_LIMIT_CNT_MAX		(1024+64)
#define CHIP_INTERNAL_PRIORITY_MAX		7
#define CHIP_PRIORITY_TO_QUEUE_GROUP_IDX_MAX	 3
#define CHIP_PRI_SEL_GROUP_INDEX_MAX	2
#define CHIP_MAX_NUM_OF_METERING		64
#define CHIP_METER_BUCKETSIZE_MAX		0XFFFF
#define CHIP_RATE_MAX				(0x1FFFF * 8)
#define	CHIP_CLASSIFY_ENTRY_MAX		512
#define	CHIP_CLASSIFY_SID_MAX		128
#define	CHIP_CLASSIFY_L4PORT_RANGE_NUM	8
#define	CHIP_CLASSIFY_IP_RANGE_NUM	8
#define	CHIP_MAX_NUM_OF_ACL_TEMPLATE	4
#define	CHIP_MAX_NUM_OF_ACL_RULE_FIELD	8
#define	CHIP_MAX_NUM_OF_ACL_ACTION	128
#define	CHIP_MAX_NUM_OF_ACL_RULE_ENTRY	64
#define	CHIP_MAX_NUM_OF_METER		32
#define	CHIP_MAX_NUM_OF_PON_QUEUE	128
#define	CHIP_MIN_NUM_OF_PON_QUEUE	1
#define	CHIP_GPON_TCONT_MAX		32
#define	CHIP_GPON_FLOW_MAX		128
#define	CHIP_PONMAC_TCONT_QUEUE_MAX	32
#define CHIP_PONMAC_PIR_CIR_RATE_MAX	0X1FFFF
#define	CHIP_MAX_LLID_ENTRY		8
#define	CHIP_GPON_OMCI_TCONT_ID		0
#define	CHIP_GPON_OMCI_QUEUE_ID		0
#define	CHIP_GPON_OMCI_FLOW_ID		0
#define CHIP_SCHID_MAX			(CHIP_GPON_TCONT_MAX-1)
#define CHIP_GPON_OMCI_PQ_ID		(CHIP_GPON_OMCI_QUEUE_ID)
#define CHIP_CLASSIFY_ENTRY_P0A0_TOTAL	64	// area0:64
#define CHIP_CLASSIFY_ENTRY_P0A1_TOTAL	64	// area1:64
#define CHIP_CLASSIFY_ENTRY_P0_TOTAL	(CHIP_CLASSIFY_ENTRY_P0A0_TOTAL+CHIP_CLASSIFY_ENTRY_P0A1_TOTAL)
#define CHIP_CLASSIFY_ENTRY_P1_TOTAL	(CHIP_CLASSIFY_ENTRY_MAX-CHIP_CLASSIFY_ENTRY_P0_TOTAL)	// area2

#else

#define CHIP_NAME			"Unknown"
#define CHIP_PON_PORTID			4
#define CHIP_PORTMASK			0x7F		// uni:0..3, pon:4, rgmii:5, cpu:6
#define CHIP_EXTPORTMASK		0x3F		// 0..5
#define CHIP_PORT_TOTAL			7
#define CHIP_RG_PORT_TOTAL		12
#define CHIP_GPON_TCONT_GROUP		4
#define CHIP_L2_LEARN_LIMIT_CNT_MAX		(2048+64)
#define CHIP_INTERNAL_PRIORITY_MAX		7
#define CHIP_PRIORITY_TO_QUEUE_GROUP_IDX_MAX	 3
#define CHIP_PRI_SEL_GROUP_INDEX_MAX	2
#define CHIP_MAX_NUM_OF_METERING		32
#define CHIP_METER_BUCKETSIZE_MAX		0XFFFF
#define CHIP_RATE_MAX				(0x1FFFF * 8)
#define	CHIP_CLASSIFY_ENTRY_MAX		512
#define	CHIP_CLASSIFY_SID_MAX		128
#define	CHIP_CLASSIFY_L4PORT_RANGE_NUM	8
#define	CHIP_CLASSIFY_IP_RANGE_NUM	8
#define	CHIP_MAX_NUM_OF_ACL_TEMPLATE	4
#define	CHIP_MAX_NUM_OF_ACL_RULE_FIELD	8
#define	CHIP_MAX_NUM_OF_ACL_ACTION	128
#define	CHIP_MAX_NUM_OF_ACL_RULE_ENTRY	64
#define	CHIP_MAX_NUM_OF_METER		32
#define	CHIP_MAX_NUM_OF_PON_QUEUE	128
#define	CHIP_MIN_NUM_OF_PON_QUEUE	1
#define	CHIP_GPON_TCONT_MAX		32
#define	CHIP_GPON_FLOW_MAX		128
#define	CHIP_PONMAC_TCONT_QUEUE_MAX	32
#define CHIP_PONMAC_PIR_CIR_RATE_MAX	0X1FFFF
#define	CHIP_MAX_LLID_ENTRY		8
#define	CHIP_GPON_OMCI_TCONT_ID		31
#define	CHIP_GPON_OMCI_QUEUE_ID		24
#define	CHIP_GPON_OMCI_FLOW_ID		127
#define CHIP_SCHID_MAX			(CHIP_GPON_TCONT_MAX-1)
#define CHIP_GPON_OMCI_PQ_ID		(3*CHIP_PONMAC_TCONT_QUEUE_MAX+CHIP_GPON_OMCI_QUEUE_ID)
#define CHIP_CLASSIFY_ENTRY_P0A0_TOTAL	64	// area0:64
#define CHIP_CLASSIFY_ENTRY_P0A1_TOTAL	64	// area1:64
#define CHIP_CLASSIFY_ENTRY_P0_TOTAL	(CHIP_CLASSIFY_ENTRY_P0A0_TOTAL+CHIP_CLASSIFY_ENTRY_P0A1_TOTAL)
#define CHIP_CLASSIFY_ENTRY_P1_TOTAL	(CHIP_CLASSIFY_ENTRY_MAX-CHIP_CLASSIFY_ENTRY_P0_TOTAL)	// area2

#endif

#endif
