/******************************************************************
 *
 * Copyright (C) 2011 5V Technologies Ltd.
 * All Rights Reserved.
 *
 * This program is the proprietary software of 5V Technologies Ltd
 * and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from 5VT.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 * Purpose : 5VT OMCI protocol stack
 * Module  : me_related
 * File    : me_related.h
 *
 ******************************************************************/

#ifndef __ME_RELATED_H__
#define __ME_RELATED_H__

#include "list.h"
#include "meinfo.h"

#define ME_RELATED_HASH_SIZE	312
//#define ME_RELATED_HASH_SIZE	64

#define ME_RELATED_FUNC_SPEC	0
#define ME_RELATED_FUNC_HW	1

struct me_related_entity_t {
	unsigned short class1;
	unsigned short class2;
	int (*spec_related_func) (struct me_t *me_ptr1, struct me_t *me_ptr2);
	int (*hw_related_func) (struct me_t *me_ptr1, struct me_t *me_ptr2);
	struct list_head entity_node;
};

/* me_related.c */
void me_related_preinit(void);
struct me_related_entity_t *me_related_find(unsigned short class1, unsigned short class2);
int me_related_add(unsigned char functype, unsigned short class1, unsigned short class2, int (*related_func)(struct me_t *me1, struct me_t *me2));
int me_related_del(unsigned short class1, unsigned short class2);
int me_related_dump(int fd);
int me_related(struct me_t *me1, struct me_t *me2);
struct me_t *me_related_find_parent_me(struct me_t *child_me, unsigned short parent_classid);
struct me_t *me_related_find_child_me(struct me_t *parent_me, unsigned short child_classid);
int  me_related_277_upstream(struct me_t *me);
int me_related_init(void);

// the following prototyping are generated by "cproto me_related_???.c"

/* me_related_002.c */
int me_related_002_256(struct me_t *me1, struct me_t *me2);
/* me_related_005.c */
int me_related_005_006(struct me_t *me1, struct me_t *me2);
int me_related_005_007(struct me_t *me1, struct me_t *me2);
int me_related_005_011(struct me_t *me1, struct me_t *me2);
int me_related_005_045(struct me_t *me1, struct me_t *me2);
int me_related_005_262(struct me_t *me1, struct me_t *me2);
int me_related_005_263(struct me_t *me1, struct me_t *me2);
/* me_related_006.c */
int me_related_006_005(struct me_t *me1, struct me_t *me2);
int me_related_006_011(struct me_t *me1, struct me_t *me2);
int me_related_006_045(struct me_t *me1, struct me_t *me2);
int me_related_006_047(struct me_t *me1, struct me_t *me2);
int me_related_006_256(struct me_t *me1, struct me_t *me2);
int me_related_006_278(struct me_t *me1, struct me_t *me2);
/* me_related_007.c */
int me_related_007_005(struct me_t *me1, struct me_t *me2);
int me_related_007_256(struct me_t *me1, struct me_t *me2);
/* me_related_011.c */
int me_related_011_005(struct me_t *me1, struct me_t *me2);
int me_related_011_006(struct me_t *me1, struct me_t *me2);
int me_related_011_024(struct me_t *me1, struct me_t *me2);
int me_related_011_047(struct me_t *me1, struct me_t *me2);
int me_related_011_264(struct me_t *me1, struct me_t *me2);
int me_related_011_290(struct me_t *me1, struct me_t *me2);
int me_related_011_296(struct me_t *me1, struct me_t *me2);
int me_related_011_334(struct me_t *me1, struct me_t *me2);
int me_related_011_349(struct me_t *me1, struct me_t *me2);
int me_related_011_425(struct me_t *me1, struct me_t *me2);
/* me_related_024.c */
int me_related_024_011(struct me_t *me1, struct me_t *me2);
int me_related_024_273(struct me_t *me1, struct me_t *me2);
int me_related_024_274(struct me_t *me1, struct me_t *me2);
/* me_related_045.c */
int me_related_045_005(struct me_t *me1, struct me_t *me2);
int me_related_045_006(struct me_t *me1, struct me_t *me2);
int me_related_045_046(struct me_t *me1, struct me_t *me2);
int me_related_045_047(struct me_t *me1, struct me_t *me2);
int me_related_045_051(struct me_t *me1, struct me_t *me2);
int me_related_045_130(struct me_t *me1, struct me_t *me2);
int me_related_045_298(struct me_t *me1, struct me_t *me2);
int me_related_045_301(struct me_t *me1, struct me_t *me2);
int me_related_045_305(struct me_t *me1, struct me_t *me2);
/* me_related_046.c */
int me_related_046_045(struct me_t *me1, struct me_t *me2);
int me_related_046_298(struct me_t *me1, struct me_t *me2);
/* me_related_047.c */
int me_related_047_006(struct me_t *me1, struct me_t *me2);
int me_related_047_045(struct me_t *me1, struct me_t *me2);
int me_related_047_011(struct me_t *me1, struct me_t *me2);
int me_related_047_130(struct me_t *me1, struct me_t *me2);
int me_related_047_134(struct me_t *me1, struct me_t *me2);
int me_related_047_266(struct me_t *me1, struct me_t *me2);
int me_related_047_280(struct me_t *me1, struct me_t *me2);
int me_related_047_281(struct me_t *me1, struct me_t *me2);
int me_related_047_048(struct me_t *me1, struct me_t *me2);
int me_related_047_049(struct me_t *me1, struct me_t *me2);
int me_related_047_079(struct me_t *me1, struct me_t *me2);
int me_related_047_050(struct me_t *me1, struct me_t *me2);
int me_related_047_052(struct me_t *me1, struct me_t *me2);
int me_related_047_084(struct me_t *me1, struct me_t *me2);
int me_related_047_302(struct me_t *me1, struct me_t *me2);
int me_related_047_310(struct me_t *me1, struct me_t *me2);
int me_related_047_311(struct me_t *me1, struct me_t *me2);
int me_related_047_321(struct me_t *me1, struct me_t *me2);
int me_related_047_322(struct me_t *me1, struct me_t *me2);
int me_related_047_329(struct me_t *me1, struct me_t *me2);
/* me_related_048.c */
int me_related_048_047(struct me_t *me1, struct me_t *me2);
/* me_related_049.c */
int me_related_049_047(struct me_t *me1, struct me_t *me2);
/* me_related_050.c */
int me_related_050_047(struct me_t *me1, struct me_t *me2);
/* me_related_051.c */
int me_related_051_045(struct me_t *me1, struct me_t *me2);
int me_related_051_273(struct me_t *me1, struct me_t *me2);
int me_related_051_274(struct me_t *me1, struct me_t *me2);
/* me_related_052.c */
int me_related_052_047(struct me_t *me1, struct me_t *me2);
int me_related_052_273(struct me_t *me1, struct me_t *me2);
int me_related_052_274(struct me_t *me1, struct me_t *me2);
/* me_related_053.c */
int me_related_053_140(struct me_t *me1, struct me_t *me2);
int me_related_053_141(struct me_t *me1, struct me_t *me2);
int me_related_053_144(struct me_t *me1, struct me_t *me2);
int me_related_053_266(struct me_t *me1, struct me_t *me2);
int me_related_053_273(struct me_t *me1, struct me_t *me2);
int me_related_053_274(struct me_t *me1, struct me_t *me2);
/* me_related_078.c */
int me_related_078_011(struct me_t *me1, struct me_t *me2);
int me_related_078_130(struct me_t *me1, struct me_t *me2);
int me_related_078_134(struct me_t *me1, struct me_t *me2);
int me_related_078_047(struct me_t *me1, struct me_t *me2);
int me_related_078_266(struct me_t *me1, struct me_t *me2);
int me_related_078_281(struct me_t *me1, struct me_t *me2);
int me_related_078_329(struct me_t *me1, struct me_t *me2);
/* me_related_079.c */
int me_related_079_047(struct me_t *me1, struct me_t *me2);
/* me_related_084.c */
int me_related_084_047(struct me_t *me1, struct me_t *me2);
int me_related_084_300(struct me_t *me1, struct me_t *me2);
/* me_related_089.c */
int me_related_089_011(struct me_t *me1, struct me_t *me2);
int me_related_089_273(struct me_t *me1, struct me_t *me2);
int me_related_089_274(struct me_t *me1, struct me_t *me2);
/* me_related_130.c */
int me_related_130_011(struct me_t *me1, struct me_t *me2);
int me_related_130_045(struct me_t *me1, struct me_t *me2);
int me_related_130_266(struct me_t *me1, struct me_t *me2);
int me_related_130_277(struct me_t *me1, struct me_t *me2);
int me_related_130_298(struct me_t *me1, struct me_t *me2);
int me_related_130_301(struct me_t *me1, struct me_t *me2);
int me_related_130_302(struct me_t *me1, struct me_t *me2);
int me_related_130_305(struct me_t *me1, struct me_t *me2);
int me_related_130_310(struct me_t *me1, struct me_t *me2);
int me_related_130_311(struct me_t *me1, struct me_t *me2);
int me_related_130_329(struct me_t *me1, struct me_t *me2);
/* me_related_131.c */
int me_related_131_256(struct me_t *me1, struct me_t *me2);
/* me_related_133.c */
int me_related_133_256(struct me_t *me1, struct me_t *me2);
/* me_related_136.c */
int me_related_136_134(struct me_t *me1, struct me_t *me2);
int me_related_136_329(struct me_t *me1, struct me_t *me2);
/* me_related_137c */
int me_related_137_148(struct me_t *me1, struct me_t *me2);
int me_related_137_157(struct me_t *me1, struct me_t *me2);
int me_related_137_340(struct me_t *me1, struct me_t *me2);
/* me_related_139.c */
int me_related_139_153(struct me_t *me1, struct me_t *me2);
int me_related_139_053(struct me_t *me1, struct me_t *me2);
int me_related_139_142(struct me_t *me1, struct me_t *me2);
/* me_related_140.c */
int me_related_140_053(struct me_t *me1, struct me_t *me2);
int me_related_140_273(struct me_t *me1, struct me_t *me2);
int me_related_140_274(struct me_t *me1, struct me_t *me2);
/* me_related_141.c */
int me_related_141_053(struct me_t *me1, struct me_t *me2);
/* me_related_142.c */
int me_related_142_058(struct me_t *me1, struct me_t *me2);
int me_related_142_143(struct me_t *me1, struct me_t *me2);
/* me_related_144.c */
int me_related_144_053(struct me_t *me1, struct me_t *me2);
int me_related_144_273(struct me_t *me1, struct me_t *me2);
int me_related_144_274(struct me_t *me1, struct me_t *me2);
/* me_related_148.c */
int me_related_148_137(struct me_t *me1, struct me_t *me2);
/* me_related_150.c */
int me_related_150_136(struct me_t *me1, struct me_t *me2);
int me_related_150_151(struct me_t *me1, struct me_t *me2);
int me_related_150_152(struct me_t *me1, struct me_t *me2);
int me_related_150_273(struct me_t *me1, struct me_t *me2);
int me_related_150_274(struct me_t *me1, struct me_t *me2);
/* me_related_151.c */
int me_related_151_150(struct me_t *me1, struct me_t *me2);
int me_related_151_273(struct me_t *me1, struct me_t *me2);
int me_related_151_274(struct me_t *me1, struct me_t *me2);
/* me_related_152.c */
int me_related_152_150(struct me_t *me1, struct me_t *me2);
int me_related_152_273(struct me_t *me1, struct me_t *me2);
int me_related_152_274(struct me_t *me1, struct me_t *me2);
/* me_related_153.c */
int me_related_153_053(struct me_t *me1, struct me_t *me2);
int me_related_153_145(struct me_t *me1, struct me_t *me2);
int me_related_153_146(struct me_t *me1, struct me_t *me2);
int me_related_153_147(struct me_t *me1, struct me_t *me2);
int me_related_153_150(struct me_t *me1, struct me_t *me2);
/* me_related_157.c */
int me_related_157_137(struct me_t *me1, struct me_t *me2);
/* me_related_160.c */
int me_related_160_256(struct me_t *me1, struct me_t *me2);
/* me_related_171.c */
int me_related_171_047(struct me_t *me1, struct me_t *me2);
int me_related_171_130(struct me_t *me1, struct me_t *me2);
int me_related_171_011(struct me_t *me1, struct me_t *me2);
int me_related_171_266(struct me_t *me1, struct me_t *me2);
int me_related_171_281(struct me_t *me1, struct me_t *me2);
int me_related_171_329(struct me_t *me1, struct me_t *me2);
/* me_related_256.c */
int me_related_256_002(struct me_t *me1, struct me_t *me2);
int me_related_256_006(struct me_t *me1, struct me_t *me2);
int me_related_256_007(struct me_t *me1, struct me_t *me2);
int me_related_256_131(struct me_t *me1, struct me_t *me2);
int me_related_256_133(struct me_t *me1, struct me_t *me2);
int me_related_256_160(struct me_t *me1, struct me_t *me2);
int me_related_256_257(struct me_t *me1, struct me_t *me2);
/* me_related_257.c */
int me_related_257_256(struct me_t *me1, struct me_t *me2);
/* me_related_262.c */
int me_related_262_005(struct me_t *me1, struct me_t *me2);
int me_related_262_277(struct me_t *me1, struct me_t *me2);
/* me_related_263.c */
int me_related_263_005(struct me_t *me1, struct me_t *me2);
int me_related_263_312(struct me_t *me1, struct me_t *me2);
/* me_related_264.c */
int me_related_264_011(struct me_t *me1, struct me_t *me2);
int me_related_264_329(struct me_t *me1, struct me_t *me2);
/* me_related_266.c */
int me_related_266_268(struct me_t *me1, struct me_t *me2);
int me_related_266_021(struct me_t *me1, struct me_t *me2);
int me_related_266_045(struct me_t *me1, struct me_t *me2);
int me_related_266_068(struct me_t *me1, struct me_t *me2);
int me_related_266_128(struct me_t *me1, struct me_t *me2);
int me_related_266_130(struct me_t *me1, struct me_t *me2);
int me_related_266_011(struct me_t *me1, struct me_t *me2);
int me_related_266_012(struct me_t *me1, struct me_t *me2);
int me_related_266_013(struct me_t *me1, struct me_t *me2);
int me_related_266_294(struct me_t *me1, struct me_t *me2);
int me_related_266_271(struct me_t *me1, struct me_t *me2);
int me_related_266_272(struct me_t *me1, struct me_t *me2);
/* me_related_267.c */
int me_related_267_268(struct me_t *me1, struct me_t *me2);
int me_related_267_273(struct me_t *me1, struct me_t *me2);
int me_related_267_274(struct me_t *me1, struct me_t *me2);
/* me_related_268.c */
int me_related_268_262(struct me_t *me1, struct me_t *me2);
int me_related_268_267(struct me_t *me1, struct me_t *me2);
int me_related_268_277(struct me_t *me1, struct me_t *me2);
int me_related_268_280(struct me_t *me1, struct me_t *me2);
int me_related_268_329(struct me_t *me1, struct me_t *me2);
int me_related_268_401(struct me_t *me1, struct me_t *me2);
int me_related_268_402(struct me_t *me1, struct me_t *me2);
/* me_related_272.c */
int me_related_272_276(struct me_t *me1, struct me_t *me2);
/* me_related_276.c */
int me_related_276_272(struct me_t *me1, struct me_t *me2);
int me_related_276_273(struct me_t *me1, struct me_t *me2);
int me_related_276_274(struct me_t *me1, struct me_t *me2);
/* me_related_277.c */
int me_related_277_011(struct me_t *me1, struct me_t *me2);
int me_related_277_130(struct me_t *me1, struct me_t *me2);
int me_related_277_262(struct me_t *me1, struct me_t *me2);
int me_related_277_278(struct me_t *me1, struct me_t *me2);
int me_related_277_329(struct me_t *me1, struct me_t *me2);
int me_related_277_401(struct me_t *me1, struct me_t *me2);
int me_related_277_402(struct me_t *me1, struct me_t *me2);
/* me_related_278.c */
int me_related_278_006(struct me_t *me1, struct me_t *me2);
int me_related_278_262(struct me_t *me1, struct me_t *me2);
int me_related_278_278(struct me_t *me1, struct me_t *me2);
/* me_related_280.c */
int me_related_280_298(struct me_t *me1, struct me_t *me2);
int me_related_280_401(struct me_t *me1, struct me_t *me2);
int me_related_280_402(struct me_t *me1, struct me_t *me2);
int me_related_280_403(struct me_t *me1, struct me_t *me2);
int me_related_280_404(struct me_t *me1, struct me_t *me2);
/* me_related_281.c */
int me_related_281_268(struct me_t *me1, struct me_t *me2);
int me_related_281_045(struct me_t *me1, struct me_t *me2);
int me_related_281_068(struct me_t *me1, struct me_t *me2);
int me_related_281_130(struct me_t *me1, struct me_t *me2);
int me_related_281_272(struct me_t *me1, struct me_t *me2);
/* me_related_290.c */
int me_related_290_011(struct me_t *me1, struct me_t *me2);
/* me_related_296.c */
int me_related_296_011(struct me_t *me1, struct me_t *me2);
int me_related_296_273(struct me_t *me1, struct me_t *me2);
int me_related_296_274(struct me_t *me1, struct me_t *me2);
/* me_related_298.c */
int me_related_298_045(struct me_t *me1, struct me_t *me2);
int me_related_298_046(struct me_t *me1, struct me_t *me2);
int me_related_298_130(struct me_t *me1, struct me_t *me2);
int me_related_298_280(struct me_t *me1, struct me_t *me2);
/* me_related_299.c */
int me_related_299_300(struct me_t *me1, struct me_t *me2);
/* me_related_300.c */
int me_related_300_084(struct me_t *me1, struct me_t *me2);
int me_related_300_299(struct me_t *me1, struct me_t *me2);
int me_related_300_302(struct me_t *me1, struct me_t *me2);
/* me_related_301.c */
int me_related_301_045(struct me_t *me1, struct me_t *me2);
int me_related_301_130(struct me_t *me1, struct me_t *me2);
/* me_related_302.c */
int me_related_302_047(struct me_t *me1, struct me_t *me2);
int me_related_302_130(struct me_t *me1, struct me_t *me2);
int me_related_302_300(struct me_t *me1, struct me_t *me2);
int me_related_302_303(struct me_t *me1, struct me_t *me2);
int me_related_302_304(struct me_t *me1, struct me_t *me2);
/* me_related_303.c */
int me_related_303_302(struct me_t *me1, struct me_t *me2);
/* me_related_304.c */
int me_related_304_302(struct me_t *me1, struct me_t *me2);
/* me_related_305.c */
int me_related_305_045(struct me_t *me1, struct me_t *me2);
int me_related_305_130(struct me_t *me1, struct me_t *me2);
/* me_related_309.c */
int me_related_309_310(struct me_t *me1, struct me_t *me2);
/* me_related_310.c */
int me_related_310_047(struct me_t *me1, struct me_t *me2);
int me_related_310_130(struct me_t *me1, struct me_t *me2);
int me_related_310_309(struct me_t *me1, struct me_t *me2);
/* me_related_311.c */
int me_related_311_047(struct me_t *me1, struct me_t *me2);
int me_related_311_130(struct me_t *me1, struct me_t *me2);
/* me_related_312.c */
int me_related_312_263(struct me_t *me1, struct me_t *me2);
int me_related_312_273(struct me_t *me1, struct me_t *me2);
int me_related_312_274(struct me_t *me1, struct me_t *me2);
/* me_related_321.c */
int me_related_321_047(struct me_t *me1, struct me_t *me2);
int me_related_321_273(struct me_t *me1, struct me_t *me2);
int me_related_321_274(struct me_t *me1, struct me_t *me2);
/* me_related_322.c */
int me_related_322_047(struct me_t *me1, struct me_t *me2);
int me_related_322_273(struct me_t *me1, struct me_t *me2);
int me_related_322_274(struct me_t *me1, struct me_t *me2);
/* me_related_329.c */
int me_related_329_047(struct me_t *me1, struct me_t *me2);
int me_related_329_134(struct me_t *me1, struct me_t *me2);
int me_related_329_136(struct me_t *me1, struct me_t *me2);
int me_related_329_268(struct me_t *me1, struct me_t *me2);
int me_related_329_330(struct me_t *me1, struct me_t *me2);
int me_related_329_340(struct me_t *me1, struct me_t *me2);
/* me_related_330.c */
int me_related_330_329(struct me_t *me1, struct me_t *me2);
/* me_related_334.c */
int me_related_334_011(struct me_t *me1, struct me_t *me2);
int me_related_334_274(struct me_t *me1, struct me_t *me2);
int me_related_334_273(struct me_t *me1, struct me_t *me2);
/* me_related_340.c */
int me_related_340_137(struct me_t *me1, struct me_t *me2);
int me_related_340_329(struct me_t *me1, struct me_t *me2);
/* me_related_349.c */
int me_related_349_011(struct me_t *me1, struct me_t *me2);
/* me_related_425.c */
int me_related_425_011(struct me_t *me1, struct me_t *me2);
int me_related_425_426(struct me_t *me1, struct me_t *me2);
#endif
