/******************************************************************
 *
 * Copyright (C) 2011 5V Technologies Ltd.
 * All Rights Reserved.
 *
 * This program is the proprietary software of 5V Technologies Ltd
 * and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from 5VT.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 * Purpose : 5VT OMCI protocol stack
 * Module  : er_group_hw
 * File    : er_group_hw.h
 *
 ******************************************************************/

#ifndef __ER_GROUP_HW_H__
#define __ER_GROUP_HW_H__

#include "voip_hw.h"
#include "omciutil_vlan.h"
#include "er_group.h"

#define ER_GROUP_HW_VLAN_TABLE_ENTRY_SIZE 192
#define ER_GROUP_HW_VLAN_DEFAULT_ENTRY 252 // 253~255: for all ports default rules, 247~252: for uni0 and uni1 default drop rules
#define ER_GROUP_HW_VLAN_PORT_NUM 12

extern unsigned short er_group_hw_util_vlan_empty_entry_num_tx;
extern unsigned short er_group_hw_util_vlan_empty_entry_num_rx;

struct tci_t {
	unsigned short pbit:3;
	unsigned short de:1;
	unsigned short vid:12;
};

// below is generated by cproto *.c in e_group_hw/ directory

/* er_group_hw_11_130_266_268_277_171_401.c */
int er_group_hw_l2s_unipqmap_802_1p_exttagop(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11_130_266_268_277_401.c */
int er_group_hw_l2s_unipqmap_802_1p(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11_130_266_268_277_78_401.c */
int er_group_hw_l2s_unipqmap_802_1p_tagop(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11_290.c */
int er_group_hw_dot1x(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_dot1x_dir(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_290_291.c */
int er_group_hw_dot1x_config(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11_47_171.c */
int er_group_hw_l2s_dscp_vlan_tagging_rxtagging_map_pptp_uni(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_tags_create_add012_pptp_uni(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11_47_78.c */
int er_group_hw_l2s_tags_create_add01_pptp_uni(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11_47.c */
int er_group_hw_ethernet_macaddr(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_11.c */
int er_group_hw_ethernet_autoneg_mode(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_phy_loopback(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_ethernet_enable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_ethernet_mtu(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_ethernet_setpause(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_bridging_pppoe_filt(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_loopdetect_enable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_bridge_router_mode(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_poe_control(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_130_280_298.c */
int er_group_hw_storm_control_dup_unknow_unicast(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_storm_control_dup_broadcast(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_storm_control_dup_unknow_multicast(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_131.c */
int er_group_hw_olt_vendor_check(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_timeofday_info(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_137_148_157_340.c */
int er_group_hw_tr069_config(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_134.c */
char *compile(char *__restrict instring, char *__restrict expbuf, __const char *__restrict endbuf, int eof);
int er_group_hw_ip_host_config_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_138.c */
int er_group_hw_voip_config_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_149.c */
int er_group_hw_sip_config_portal(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_256.c */
int er_group_hw_mac_traffic_control_mng_option(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_262_277_278_402.c */
int er_group_hw_mac_traffic_control_pq_ts_tcont(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_262_278.c */
int er_group_hw_mac_traffic_control_first_ts(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_262.c */
int er_group_hw_mac_traffic_control_second_ts(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_mac_tcont_allocate(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_263.c */
int er_group_hw_mac_gem_block(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_mac_bip_setsdsf(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_268_277.c */
int er_group_hw_generator_pq_ts_tcont(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_268_280_401.c */
int er_group_hw_mac_traffic_control_td_ds_gem(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_277_402.c */
int er_group_hw_mac_traffic_control_red(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_300.c */
int er_group_hw_l2s_tags_create_add012_cfm(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_45_280_298.c */
int er_group_hw_port_storm_control(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2], int pkt_type);
int er_group_hw_port_storm_control_unknow_unicast(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_port_storm_control_broadcast(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_port_storm_control_unknow_multicast(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_45_47_49.c */
int er_group_hw_l2s_mac_table_create_del(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_45_47_79.c */
int er_group_hw_l2s_preassign_filt(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_45_47_84.c */
int er_group_hw_l2s_filt_configure(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_filt_create_vid_tci_pri(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_45_47.c */
int er_group_hw_l2s_bridging_localbridging(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_mac_table_assign(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_mac_table_flood(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_mac_learning_depth_by_port(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_tags_create_add012_bridge_port_add(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_45.c */
int er_group_hw_l2s_mac_aging_time(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
#if defined CONFIG_SDK_PRX126 || defined CONFIG_SDK_PRX120 || defined CONFIG_SDK_PRX321
int er_group_hw_l2s_bridge_inf(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_47_entity_set(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
#endif
/* er_group_hw_47_130_171.c */
int er_group_hw_l2s_dscp_vlan_tagging_rxtagging_map_802_1p(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_tags_create_add012_802_1p(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_130_262_266_268_277_280_402.c */
int er_group_hw_mac_traffic_control_td_us_gem_802_1p_tm_rate_controlled(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_130_262_266_268_277_402.c */
int er_group_hw_mac_gem_bridge_allocate_802_1p_tm_rate_controlled(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_130_266_268_277_280_402.c */
int er_group_hw_mac_traffic_control_td_us_gem_802_1p(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_130_266_268_277_402.c */
int er_group_hw_mac_gem_bridge_allocate_802_1p(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_130_299_300_302.c */
int er_group_hw_cfm_mapper_info(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_130.c */
int er_group_hw_l2s_dscp_port_enable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_dscp_port_map(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_dscp_port_default(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_134_171.c */
int er_group_hw_l2s_dscp_vlan_tagging_rxtagging_map_ip_host(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_tags_create_add012_ip_host(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_171_329.c */
int er_group_hw_l2s_dscp_vlan_tagging_rxtagging_map_veip(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_tags_create_add012_veip(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_171.c */
int er_group_hw_l2s_dscp_vlan_tagging_rxtagging_map_bridge(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_l2s_tags_create_add012_bridge(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_262_266_268_277_280_402.c */
int er_group_hw_mac_traffic_control_td_us_gem_iwtp_tm_rate_controlled(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_262_266_268_277_402.c */
int er_group_hw_mac_gem_bridge_allocate_gem_iw_tp_tm_rate_controlled(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_266_268_277_280_402.c */
int er_group_hw_mac_traffic_control_td_us_gem_iwtp(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_266_268_277_402.c */
int er_group_hw_mac_gem_bridge_allocate_gem_iw_tp(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_266_268_401.c */
int er_group_hw_mac_gem_bridge_allocate_broadcast_gem_iw_tp(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_280_403.c */
int er_group_hw_mac_traffic_control_td_inbound(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_280_404.c */
int er_group_hw_mac_traffic_control_td_outbound(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_281_268.c */
int er_group_hw_mac_gem_bridge_allocate_multicast_gem_iw_tp(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_299_300_302.c */
int er_group_hw_new_mep_by_vlan(int action, struct er_attr_group_instance_t *attr_inst);
unsigned short er_group_hw_find_uni_bp(unsigned short bridge_ptr);
int er_group_hw_cfm_bridge_info(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_309_310.c */
int er_group_hw_l2s_tags_create_add01_multicast_309(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_igmp_upstream_rate_set(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_igmp_max_membership(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_max_multicast_bandwidth_set(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_static_acl_table(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_mcast_conf_set(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
/* er_group_hw_47_78_130.c */
int er_group_hw_l2s_tags_create_add01_802_1p(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_78_134.c */
int er_group_hw_l2s_tags_create_add01_ip_host(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_78_329.c */
int er_group_hw_l2s_tags_create_add01_veip(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_78.c */
int er_group_hw_l2s_tags_create_add01_bridge(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_84_299_300.c */
int er_group_hw_get_mac_addr(unsigned char *mac, char *devname);
int er_group_hw_cfm_mip_info(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_47_329.c */
int er_group_hw_sync_veip_autouni_admin_state(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_134_136_150_153.c */
int er_group_hw_sip_agent_config_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_139_142_143.c */
int er_group_hw_rtp_profile_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_139_142.c */
int er_group_hw_voip_media_profile(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_139.c */
int er_group_hw_voip_voice_ctp(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_140.c */
int er_group_hw_call_control_performance_monitoring_history_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_141.c */
int er_group_hw_voip_line_status(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_144.c */
int er_group_hw_rtp_performance_monitoring_history_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_145_153.c */
int er_group_hw_network_dial_plan_table(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_146_153.c */
int er_group_hw_voip_application_service_profile(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_147_153.c */
int er_group_hw_voip_feature_access_codes(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_150_151_153.c */
int er_group_hw_sip_agent_performance_monitoring_history_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_150_152_153.c */
int er_group_hw_sip_call_initiation_performance_monitoring_history_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_153.c */
int er_group_hw_sip_user_data(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53_58_139_142.c */
int er_group_hw_voice_service_profile(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_53.c */
int er_group_hw_physical_path_termination_point_pots_uni(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_6_47_48.c */
int er_group_hw_l2s_bridging_stp_portstate(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_7.c */
int er_group_hw_set_bootenv(unsigned char parameter, unsigned char value);
int er_group_hw_update_commit_env(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_update_active_env(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_update_valid_env(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_158.c */
int er_group_hw_remote_debug(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw.c */
int er_group_hw_init(void);

/* er_group_hw_util.c */
int er_group_hw_util_config_dscp2pbit_table(unsigned int portmask, char *omci_dscp2pbit_bitmap);

/* er_group_hw_voip_wrapper.c */
int er_group_hw_voip_wrapper_physical_path_termination_point_pots_uni(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_physical_path_termination_point_pots_uni_t *parm);
int er_group_hw_voip_wrapper_sip_user_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_sip_user_data_t *parm);
int er_group_hw_voip_wrapper_sip_agent_config_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_sip_agent_config_data_t *parm);
int er_group_hw_voip_wrapper_voip_voice_ctp(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_voice_ctp_t *parm);
int er_group_hw_voip_wrapper_voip_media_profile(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_media_profile_t *parm);
int er_group_hw_voip_wrapper_voice_service_profile(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voice_service_profile_t *parm);
int er_group_hw_voip_wrapper_rtp_profile_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_rtp_profile_data_t *parm);
int er_group_hw_voip_wrapper_voip_application_service_profile(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_application_service_profile_t *parm);
int er_group_hw_voip_wrapper_voip_feature_access_codes(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_feature_access_codes_t *parm);
int er_group_hw_voip_wrapper_network_dial_plan_table(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_network_dial_plan_table_t *parm);
int er_group_hw_voip_wrapper_voip_line_status(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_line_status_t *parm);
int er_group_hw_voip_wrapper_call_control_performance_monitoring_history_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_call_control_performance_monitoring_history_data_t *parm);
int er_group_hw_voip_wrapper_rtp_performance_monitoring_history_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_rtp_performance_monitoring_history_data_t *parm);
int er_group_hw_voip_wrapper_sip_agent_performance_monitoring_history_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_sip_agent_performance_monitoring_history_data_t *parm);
int er_group_hw_voip_wrapper_sip_call_initiation_performance_monitoring_history_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_sip_call_initiation_performance_monitoring_history_data_t *parm);
int er_group_hw_voip_wrapper_voip_config_data(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_config_data_t *parm);
int er_group_hw_voip_wrapper_sip_config_portal(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_sip_config_portal_t *parm);
int er_group_hw_voip_wrapper_voip_call_statistics_extension4(enum voip_hw_action_t action, int port, unsigned char mask[2], struct voip_hw_voip_call_statistics_extension4_t *parm);

/* er_group_hw_334.c */
int er_group_hw_334_accum_disable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
/* er_group_hw_425.c */
int er_group_hw_425_accum_disable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_82.c */
int er_group_hw_video_uni_enable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_83.c */
int er_group_hw_physical_path_termination_point_lct_uni(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_90.c */
int er_group_hw_video_ani_enable(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_agc_setting(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_349.c */
int er_group_hw_poe_power_priority(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);
int er_group_hw_poe_class_control(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_153_150.c */
int er_group_hw_pots_config(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

/* er_group_hw_65283.c */
int er_group_hw_calix_voip_call_statistics_ext4(int action, struct er_attr_group_instance_t *attr_inst, struct me_t *me, unsigned char attr_mask[2]);

#endif
